# Generated by Django 5.0.2 on 2024-02-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
